/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    utilisateurs: UtilisateurAuthOperations;
    candidats: CandidatAuthOperations;
  };
  blocks: {};
  collections: {
    utilisateurs: Utilisateur;
    candidats: Candidat;
    personnes: Personne;
    candidatures: Candidature;
    pieces: Piece;
    compteurs: Compteur;
    actualites: Actualite;
    evenements: Evenement;
    offres: Offre;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    utilisateurs: UtilisateursSelect<false> | UtilisateursSelect<true>;
    candidats: CandidatsSelect<false> | CandidatsSelect<true>;
    personnes: PersonnesSelect<false> | PersonnesSelect<true>;
    candidatures: CandidaturesSelect<false> | CandidaturesSelect<true>;
    pieces: PiecesSelect<false> | PiecesSelect<true>;
    compteurs: CompteursSelect<false> | CompteursSelect<true>;
    actualites: ActualitesSelect<false> | ActualitesSelect<true>;
    evenements: EvenementsSelect<false> | EvenementsSelect<true>;
    offres: OffresSelect<false> | OffresSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en') | ('fr' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'fr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Utilisateur | Candidat;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UtilisateurAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CandidatAuthOperations {
  forgotPassword:
    | {
        email: string;
      }
    | {
        username: string;
      };
  login:
    | {
        email: string;
        password: string;
      }
    | {
        password: string;
        username: string;
      };
  registerFirstUser: {
    password: string;
    username: string;
    email?: string;
  };
  unlock:
    | {
        email: string;
      }
    | {
        username: string;
      };
}
/**
 * Les droits sont attribués par rôle. Un compte n’est jamais partagé entre plusieurs agents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "utilisateurs".
 */
export interface Utilisateur {
  id: number;
  nom: string;
  prenoms: string;
  nomComplet?: string | null;
  /**
   * Détermine l’ensemble des droits. Voir le périmètre de chaque rôle au chapitre 5.2 du cadrage.
   */
  role:
    | 'administrateur'
    | 'editeur'
    | 'redacteur'
    | 'admission'
    | 'scolarite'
    | 'finances'
    | 'consultation'
    | 'carrieres'
    | 'recherche';
  /**
   * Intitulé de poste, tel qu’il figure dans l’organigramme.
   */
  fonction?: string | null;
  /**
   * Un compte désactivé conserve son historique mais ne peut plus se connecter.
   */
  actif?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'utilisateurs';
}
/**
 * Comptes créés par les candidats eux-mêmes. Ils ne donnent accès qu’à leur propre dossier.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidats".
 */
export interface Candidat {
  id: number;
  /**
   * Rattachement au référentiel unique. Si la personne est déjà connue de l’établissement, on la rattache plutôt que de la dupliquer (§10.5).
   */
  personne?: (number | null) | Personne;
  /**
   * Sert aux notifications par message court.
   */
  telephone?: string | null;
  verifie?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'candidats';
}
/**
 * Référentiel unique. Chaque candidat, étudiant ou participant n’y existe qu’une fois, et n’en est jamais retiré.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personnes".
 */
export interface Personne {
  id: number;
  /**
   * Attribué à la première inscription, conservé au-delà du diplôme. Il n’encode ni la filière ni le niveau, et ne change jamais.
   */
  numeroEtudiant?: string | null;
  identite?: string | null;
  nom: string;
  prenoms: string;
  dateNaissance?: string | null;
  lieuNaissance?: string | null;
  nationalite?: string | null;
  sexe?: ('f' | 'm') | null;
  telephone?: string | null;
  courriel?: string | null;
  adresse?: string | null;
  contactNom?: string | null;
  contactLien?: string | null;
  contactTelephone?: string | null;
  /**
   * Consultable par les seuls rôles Admission et Scolarité. Chaque accès est journalisé.
   */
  pieceIdentite?: (number | null) | Piece;
  /**
   * Usage administratif. N’est jamais exposée au public ni à la personne concernée.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Documents déposés par les candidats. Jamais accessibles par une adresse publique.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pieces".
 */
export interface Piece {
  id: number;
  deposePar?: (number | null) | Candidat;
  nature?: ('identite' | 'releve' | 'diplome' | 'photo' | 'autre') | null;
  /**
   * §20.2 — chaque accès à une pièce est enregistré.
   */
  consultations?:
    | {
        agent?: (number | null) | Utilisateur;
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    lisible?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Dossiers déposés en ligne. Un dossier n’est jamais supprimé : il change d’état.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidatures".
 */
export interface Candidature {
  id: number;
  reference?: string | null;
  etat:
    | 'brouillon'
    | 'soumis'
    | 'instruction'
    | 'complement'
    | 'complet'
    | 'admis'
    | 'admis-condition'
    | 'attente'
    | 'refuse'
    | 'inscrit'
    | 'desiste';
  candidat?: (number | null) | Candidat;
  /**
   * Renseignée à l’admission, ou rattachée si la personne est déjà connue (§10.5).
   */
  personne?: (number | null) | Personne;
  voeu1:
    | 'bts-agriculture-tropicale-production-animale'
    | 'bts-agriculture-tropicale-production-vegetale'
    | 'bts-industrie-agroalimentaire-production'
    | 'bts-industrie-agroalimentaire-controle'
    | 'licence-production-animale-soins-veterinaires'
    | 'licence-production-vegetale-protection-cultures'
    | 'licence-fertilisation-gestion-durable-sols'
    | 'licence-genie-environnement-finance-durable'
    | 'licence-technologie-agriculture-intelligente'
    | 'licence-agribusiness-management-chaines-valeur'
    | 'licence-ingenierie-transformation-aliments'
    | 'certificat-aviculture'
    | 'certificat-porciculture'
    | 'certificat-pisciculture'
    | 'certificat-cuniculture'
    | 'certificat-aulacodiculture'
    | 'certificat-ruminants'
    | 'certificat-apiculture'
    | 'certificat-heliciculture'
    | 'certificat-maraichage-durable'
    | 'certificat-mais-manioc'
    | 'certificat-banane-associations'
    | 'certificat-agroecologie-agriculture-biologique'
    | 'certificat-myciculture'
    | 'certificat-culture-hors-sol'
    | 'masterclass-pilotage-drone'
    | 'masterclass-coeurs-de-metiers'
    | 'masterclass-projet-de-stage'
    | 'masterclass-entrepreneuriat'
    | 'masterclass-art-oratoire';
  /**
   * Facultatif. Examiné si le premier choix n’aboutit pas.
   */
  voeu2?:
    | (
        | 'bts-agriculture-tropicale-production-animale'
        | 'bts-agriculture-tropicale-production-vegetale'
        | 'bts-industrie-agroalimentaire-production'
        | 'bts-industrie-agroalimentaire-controle'
        | 'licence-production-animale-soins-veterinaires'
        | 'licence-production-vegetale-protection-cultures'
        | 'licence-fertilisation-gestion-durable-sols'
        | 'licence-genie-environnement-finance-durable'
        | 'licence-technologie-agriculture-intelligente'
        | 'licence-agribusiness-management-chaines-valeur'
        | 'licence-ingenierie-transformation-aliments'
        | 'certificat-aviculture'
        | 'certificat-porciculture'
        | 'certificat-pisciculture'
        | 'certificat-cuniculture'
        | 'certificat-aulacodiculture'
        | 'certificat-ruminants'
        | 'certificat-apiculture'
        | 'certificat-heliciculture'
        | 'certificat-maraichage-durable'
        | 'certificat-mais-manioc'
        | 'certificat-banane-associations'
        | 'certificat-agroecologie-agriculture-biologique'
        | 'certificat-myciculture'
        | 'certificat-culture-hors-sol'
        | 'masterclass-pilotage-drone'
        | 'masterclass-coeurs-de-metiers'
        | 'masterclass-projet-de-stage'
        | 'masterclass-entrepreneuriat'
        | 'masterclass-art-oratoire'
      )
    | null;
  anneeEntree?: string | null;
  nom?: string | null;
  prenoms?: string | null;
  nomCandidat?: string | null;
  dateNaissance?: string | null;
  lieuNaissance?: string | null;
  nationalite?: string | null;
  telephone?: string | null;
  courriel?: string | null;
  contactNom?: string | null;
  contactLien?: string | null;
  contactTelephone?: string | null;
  serieBac?: string | null;
  anneeBac?: string | null;
  mentionBac?: string | null;
  etablissementOrigine?: string | null;
  situation?: ('reprise' | 'salarie' | 'hebergement')[] | null;
  pieces?:
    | {
        fichier: number | Piece;
        etatPiece?: ('attente' | 'acceptee' | 'rejetee') | null;
        /**
         * Communiqué au candidat avec la demande de complément (§10.3).
         */
        motif?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Une référence déjà utilisée est rejetée par le dispositif.
   */
  referenceTransaction?: string | null;
  modeReglement?: ('mobile' | 'guichet' | 'virement') | null;
  /**
   * La validation reste humaine : un agent rapproche la référence de son relevé.
   */
  transactionVerifiee?: boolean | null;
  decisionSens?: ('admis' | 'admis-condition' | 'attente' | 'refuse') | null;
  decisionConditions?: string | null;
  decisionDate?: string | null;
  decisionAgent?: (number | null) | Utilisateur;
  /**
   * §10.3 — conserve l’auteur et la date de chaque décision.
   */
  journal?:
    | {
        date?: string | null;
        action?: string | null;
        auteur?: string | null;
        id?: string | null;
      }[]
    | null;
  soumisLe?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compteurs".
 */
export interface Compteur {
  id: number;
  sequence: string;
  valeur: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actualites".
 */
export interface Actualite {
  id: number;
  /**
   * Ce que le lecteur verra en premier. Une phrase, pas un slogan.
   */
  titre: string;
  /**
   * Déduite du titre si elle est laissée vide. Ne la changez plus une fois publiée.
   */
  slug?: string | null;
  categorie: 'etablissement' | 'admissions' | 'formations' | 'ressources' | 'partenariats';
  date: string;
  /**
   * Deux ou trois lignes. C’est ce qui s’affiche en liste et dans les résultats de recherche.
   */
  chapo: string;
  /**
   * Laissez une ligne vide entre deux paragraphes. Le site s’occupe de la mise en forme.
   */
  corps: string;
  etat: 'brouillon' | 'a-valider' | 'publie' | 'archive';
  publieLe?: string | null;
  publiePar?: (number | null) | Utilisateur;
  redigePar?: (number | null) | Utilisateur;
  /**
   * Qui a fait quoi, et quand.
   */
  journal?:
    | {
        date?: string | null;
        action?: string | null;
        auteur?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evenements".
 */
export interface Evenement {
  id: number;
  titre: string;
  /**
   * Déduite de l’intitulé si elle est laissée vide.
   */
  slug?: string | null;
  /**
   * Laissez vide tant que la date n’est pas arrêtée.
   */
  date?: string | null;
  lieu: string;
  /**
   * Quelques lignes : ce qui se passe, et pour qui.
   */
  resume: string;
  inscriptionRequise?: boolean | null;
  etat: 'brouillon' | 'a-valider' | 'publie' | 'archive';
  publieLe?: string | null;
  publiePar?: (number | null) | Utilisateur;
  redigePar?: (number | null) | Utilisateur;
  /**
   * Qui a fait quoi, et quand.
   */
  journal?:
    | {
        date?: string | null;
        action?: string | null;
        auteur?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offres".
 */
export interface Offre {
  id: number;
  intitule: string;
  /**
   * Déduite de l’intitulé si elle est laissée vide.
   */
  slug?: string | null;
  structure: string;
  lieu: string;
  type: 'stage' | 'emploi' | 'alternance';
  /**
   * Passé ce jour, l’offre disparaît d’elle-même du site public.
   */
  dateLimite: string;
  /**
   * Missions, profil attendu, conditions. Une ligne vide sépare deux paragraphes.
   */
  description: string;
  /**
   * Adresse électronique, numéro, ou consigne précise donnée par l’entreprise.
   */
  contact: string;
  etat: 'brouillon' | 'a-valider' | 'publie' | 'archive';
  publieLe?: string | null;
  publiePar?: (number | null) | Utilisateur;
  redigePar?: (number | null) | Utilisateur;
  /**
   * Qui a fait quoi, et quand.
   */
  journal?:
    | {
        date?: string | null;
        action?: string | null;
        auteur?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'utilisateurs';
        value: number | Utilisateur;
      } | null)
    | ({
        relationTo: 'candidats';
        value: number | Candidat;
      } | null)
    | ({
        relationTo: 'personnes';
        value: number | Personne;
      } | null)
    | ({
        relationTo: 'candidatures';
        value: number | Candidature;
      } | null)
    | ({
        relationTo: 'pieces';
        value: number | Piece;
      } | null)
    | ({
        relationTo: 'compteurs';
        value: number | Compteur;
      } | null)
    | ({
        relationTo: 'actualites';
        value: number | Actualite;
      } | null)
    | ({
        relationTo: 'evenements';
        value: number | Evenement;
      } | null)
    | ({
        relationTo: 'offres';
        value: number | Offre;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'utilisateurs';
        value: number | Utilisateur;
      }
    | {
        relationTo: 'candidats';
        value: number | Candidat;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'utilisateurs';
        value: number | Utilisateur;
      }
    | {
        relationTo: 'candidats';
        value: number | Candidat;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "utilisateurs_select".
 */
export interface UtilisateursSelect<T extends boolean = true> {
  nom?: T;
  prenoms?: T;
  nomComplet?: T;
  role?: T;
  fonction?: T;
  actif?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidats_select".
 */
export interface CandidatsSelect<T extends boolean = true> {
  personne?: T;
  telephone?: T;
  verifie?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personnes_select".
 */
export interface PersonnesSelect<T extends boolean = true> {
  numeroEtudiant?: T;
  identite?: T;
  nom?: T;
  prenoms?: T;
  dateNaissance?: T;
  lieuNaissance?: T;
  nationalite?: T;
  sexe?: T;
  telephone?: T;
  courriel?: T;
  adresse?: T;
  contactNom?: T;
  contactLien?: T;
  contactTelephone?: T;
  pieceIdentite?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidatures_select".
 */
export interface CandidaturesSelect<T extends boolean = true> {
  reference?: T;
  etat?: T;
  candidat?: T;
  personne?: T;
  voeu1?: T;
  voeu2?: T;
  anneeEntree?: T;
  nom?: T;
  prenoms?: T;
  nomCandidat?: T;
  dateNaissance?: T;
  lieuNaissance?: T;
  nationalite?: T;
  telephone?: T;
  courriel?: T;
  contactNom?: T;
  contactLien?: T;
  contactTelephone?: T;
  serieBac?: T;
  anneeBac?: T;
  mentionBac?: T;
  etablissementOrigine?: T;
  situation?: T;
  pieces?:
    | T
    | {
        fichier?: T;
        etatPiece?: T;
        motif?: T;
        id?: T;
      };
  referenceTransaction?: T;
  modeReglement?: T;
  transactionVerifiee?: T;
  decisionSens?: T;
  decisionConditions?: T;
  decisionDate?: T;
  decisionAgent?: T;
  journal?:
    | T
    | {
        date?: T;
        action?: T;
        auteur?: T;
        id?: T;
      };
  soumisLe?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pieces_select".
 */
export interface PiecesSelect<T extends boolean = true> {
  deposePar?: T;
  nature?: T;
  consultations?:
    | T
    | {
        agent?: T;
        date?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        lisible?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compteurs_select".
 */
export interface CompteursSelect<T extends boolean = true> {
  sequence?: T;
  valeur?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actualites_select".
 */
export interface ActualitesSelect<T extends boolean = true> {
  titre?: T;
  slug?: T;
  categorie?: T;
  date?: T;
  chapo?: T;
  corps?: T;
  etat?: T;
  publieLe?: T;
  publiePar?: T;
  redigePar?: T;
  journal?:
    | T
    | {
        date?: T;
        action?: T;
        auteur?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evenements_select".
 */
export interface EvenementsSelect<T extends boolean = true> {
  titre?: T;
  slug?: T;
  date?: T;
  lieu?: T;
  resume?: T;
  inscriptionRequise?: T;
  etat?: T;
  publieLe?: T;
  publiePar?: T;
  redigePar?: T;
  journal?:
    | T
    | {
        date?: T;
        action?: T;
        auteur?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offres_select".
 */
export interface OffresSelect<T extends boolean = true> {
  intitule?: T;
  slug?: T;
  structure?: T;
  lieu?: T;
  type?: T;
  dateLimite?: T;
  description?: T;
  contact?: T;
  etat?: T;
  publieLe?: T;
  publiePar?: T;
  redigePar?: T;
  journal?:
    | T
    | {
        date?: T;
        action?: T;
        auteur?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}